USE [MRP]
GO
/****** Object:  Table [dbo].[USER]    Script Date: 2017/1/1 ¤U¤È 11:16:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[USER](
	[USER_CODE] [varchar](20) NOT NULL,
	[USER_NAME] [nvarchar](20) NOT NULL,
	[ROLE_CODE] [varchar](10) NOT NULL,
	[EMAIL] [varchar](50) NOT NULL,
	[SALT] [varchar](128) NOT NULL,
	[PASSWORD] [varchar](256) NOT NULL,
	[ADMIN] [bit] NOT NULL,
	[ACTIVE] [bit] NOT NULL,
	[CREATE_BY] [varchar](20) NOT NULL,
	[CREATE_DT] [datetime] NOT NULL,
	[MODIFY_BY] [varchar](20) NULL,
	[MODIFY_DT] [datetime] NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[USER_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
