USE [master]
GO
/****** Object:  Database [MRP]    Script Date: 2016/11/6 下午 11:51:06 ******/
CREATE DATABASE [MRP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MRP', FILENAME = N'C:\db\mrp\MRP.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MRP_log', FILENAME = N'C:\db\mrp\MRP_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [MRP] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MRP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MRP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MRP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MRP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MRP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MRP] SET ARITHABORT OFF 
GO
ALTER DATABASE [MRP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MRP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MRP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MRP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MRP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MRP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MRP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MRP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MRP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MRP] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MRP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MRP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MRP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MRP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MRP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MRP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MRP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MRP] SET RECOVERY FULL 
GO
ALTER DATABASE [MRP] SET  MULTI_USER 
GO
ALTER DATABASE [MRP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MRP] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MRP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MRP] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [MRP] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'MRP', N'ON'
GO
USE [MRP]
GO
/****** Object:  User [mrpuser]    Script Date: 2016/11/6 下午 11:51:06 ******/
CREATE USER [mrpuser] FOR LOGIN [mrpuser] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [mrpuser]
GO
/****** Object:  Table [dbo].[CUSTOMER]    Script Date: 2016/11/6 下午 11:51:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CUSTOMER](
	[CUS_CODE] [varchar](20) NOT NULL,
	[CUS_NAME] [nvarchar](20) NOT NULL,
	[CREATE_BY] [varchar](20) NOT NULL,
	[CREATE_DT] [datetime] NOT NULL,
	[MODIFY_BY] [varchar](20) NULL,
	[MODIFY_DT] [datetime] NULL,
 CONSTRAINT [PK_CUSTOMER] PRIMARY KEY CLUSTERED 
(
	[CUS_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DAILY_SCHEDULE]    Script Date: 2016/11/6 下午 11:51:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DAILY_SCHEDULE](
	[SCHEDULE_DT] [date] NOT NULL,
	[PRO_CODE] [varchar](20) NOT NULL,
	[TARGET_AMT] [int] NOT NULL,
	[PRODUCED_AMT] [int] NULL,
	[PACKED_AMT] [int] NULL,
	[CREATE_BY] [varchar](20) NOT NULL,
	[CREATE_DT] [datetime] NOT NULL,
	[MODIFY_BY] [varchar](20) NULL,
	[MODIFY_DT] [datetime] NULL,
 CONSTRAINT [PK_DAILY_SCHEDULE] PRIMARY KEY CLUSTERED 
(
	[SCHEDULE_DT] ASC,
	[PRO_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DATESERNO]    Script Date: 2016/11/6 下午 11:51:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DATESERNO](
	[DATESER_COLNAME] [varchar](50) NOT NULL,
	[SERDATE] [datetime2](0) NOT NULL,
	[SERNO] [int] NULL,
	[CREATE_BY] [varchar](20) NOT NULL,
	[CREATE_DT] [datetime] NOT NULL,
	[MODIFY_BY] [varchar](20) NULL,
	[MODIFY_DT] [datetime] NULL,
 CONSTRAINT [PK_DATESERNO] PRIMARY KEY CLUSTERED 
(
	[DATESER_COLNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DATESERNO_SETS]    Script Date: 2016/11/6 下午 11:51:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DATESERNO_SETS](
	[DATESER_COLNAME] [varchar](50) NOT NULL,
	[PREFIX_CODE] [varchar](6) NULL,
	[SERDATE_TYPE] [varchar](1) NOT NULL,
	[SERNO_LEN] [int] NULL,
	[CONJ_SIGN] [varchar](1) NULL,
	[CREATE_BY] [varchar](20) NOT NULL,
	[CREATE_DT] [datetime] NOT NULL,
	[MODIFY_BY] [varchar](20) NULL,
	[MODIFY_DT] [datetime] NULL,
 CONSTRAINT [PK_DATESERNO_SETS] PRIMARY KEY CLUSTERED 
(
	[DATESER_COLNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MAT_STOCK]    Script Date: 2016/11/6 下午 11:51:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MAT_STOCK](
	[MAT_CODE] [varchar](20) NOT NULL,
	[AMOUNTS] [decimal](18, 6) NOT NULL,
	[CREATE_BY] [varchar](20) NOT NULL,
	[CREATE_DT] [datetime] NOT NULL,
	[MODIFY_BY] [varchar](20) NULL,
	[MODIFY_DT] [datetime] NULL,
 CONSTRAINT [PK_MAT_STOCK] PRIMARY KEY CLUSTERED 
(
	[MAT_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MATERIAL]    Script Date: 2016/11/6 下午 11:51:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MATERIAL](
	[MAT_CODE] [varchar](20) NOT NULL,
	[MAT_NAME] [nvarchar](20) NOT NULL,
	[SUPP_CODE] [varchar](20) NOT NULL,
	[UNIT_NAME] [nvarchar](20) NOT NULL,
	[CREATE_BY] [varchar](20) NOT NULL,
	[CREATE_DT] [datetime] NOT NULL,
	[MODIFY_BY] [varchar](20) NULL,
	[MODIFY_DT] [datetime] NULL,
 CONSTRAINT [PK_MATERIAL] PRIMARY KEY CLUSTERED 
(
	[MAT_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PRO_MATERIAL]    Script Date: 2016/11/6 下午 11:51:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PRO_MATERIAL](
	[PRO_CODE] [varchar](20) NOT NULL,
	[MAT_CODE] [varchar](20) NOT NULL,
	[AMOUNTS] [decimal](18, 6) NOT NULL,
	[CREATE_BY] [varchar](20) NOT NULL,
	[CREATE_DT] [datetime] NOT NULL,
	[MODIFY_BY] [varchar](20) NULL,
	[MODIFY_DT] [datetime] NULL,
 CONSTRAINT [PK_PRO_MATERIAL] PRIMARY KEY CLUSTERED 
(
	[PRO_CODE] ASC,
	[MAT_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PRODUCT]    Script Date: 2016/11/6 下午 11:51:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PRODUCT](
	[PRO_CODE] [varchar](20) NOT NULL,
	[PRO_NAME] [nvarchar](20) NOT NULL,
	[CUS_CODE] [varchar](20) NOT NULL,
	[PRO_DESC] [nvarchar](500) NOT NULL,
	[CREATE_BY] [varchar](20) NOT NULL,
	[CREATE_DT] [datetime] NOT NULL,
	[MODIFY_BY] [varchar](20) NULL,
	[MODIFY_DT] [datetime] NULL,
 CONSTRAINT [PK_PRODUCT] PRIMARY KEY CLUSTERED 
(
	[PRO_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ROLE]    Script Date: 2016/11/6 下午 11:51:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ROLE](
	[ROLE_CODE] [varchar](20) NOT NULL,
	[ROLE_NAME] [nvarchar](20) NOT NULL,
	[CREATE_BY] [varchar](20) NOT NULL,
	[CREATE_DT] [datetime] NOT NULL,
	[MODIFY_BY] [varchar](20) NULL,
	[MODIFY_DT] [datetime] NULL,
 CONSTRAINT [PK_ROLE] PRIMARY KEY CLUSTERED 
(
	[ROLE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SUPPLIER]    Script Date: 2016/11/6 下午 11:51:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SUPPLIER](
	[SUPP_CODE] [varchar](20) NOT NULL,
	[SUPP_NAME] [nvarchar](20) NOT NULL,
	[CREATE_BY] [varchar](20) NOT NULL,
	[CREATE_DT] [datetime] NOT NULL,
	[MODIFY_BY] [varchar](20) NULL,
	[MODIFY_DT] [datetime] NULL,
 CONSTRAINT [PK_SUPPLIER] PRIMARY KEY CLUSTERED 
(
	[SUPP_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[UNIT]    Script Date: 2016/11/6 下午 11:51:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[UNIT](
	[UNIT_CODE] [varchar](20) NOT NULL,
	[UNIT_NAME] [nvarchar](20) NOT NULL,
	[CREATE_BY] [varchar](20) NOT NULL,
	[CREATE_DT] [datetime] NOT NULL,
	[MODIFY_BY] [varchar](20) NULL,
	[MODIFY_DT] [datetime] NULL,
 CONSTRAINT [PK_UNIT] PRIMARY KEY CLUSTERED 
(
	[UNIT_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[USER]    Script Date: 2016/11/6 下午 11:51:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[USER](
	[USER_CODE] [varchar](20) NOT NULL,
	[USER_NAME] [nvarchar](20) NOT NULL,
	[ROLE_CODE] [varchar](10) NOT NULL,
	[EMAIL] [varchar](50) NOT NULL,
	[SALT] [varchar](128) NOT NULL,
	[PASSWORD] [varchar](256) NOT NULL,
	[ADMIN] [bit] NOT NULL,
	[ACTIVE] [bit] NOT NULL,
	[CREATE_BY] [varchar](20) NOT NULL,
	[CREATE_DT] [datetime] NOT NULL,
	[MODIFY_BY] [varchar](20) NULL,
	[MODIFY_DT] [datetime] NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[USER_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  StoredProcedure [dbo].[SP_GET_DATE_SERIAL]    Script Date: 2016/11/6 下午 11:51:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--====================================================================
--SP Name     : dbo.SP_GET_DATE_SERIAL 
--Function    : 取序號
--Author      : 
--Create Date : 
--Source Table: [1]dbo.DATESERNO
--              [2]dbo.DATESERNO_SETS
--Target Table: [1]dbo.DATESERNO
--Parameter   : [1]@I_DATESER_COLNAME
--Return Value: [1]@O_DATESER_CODE
--Exec SP Name: 
--Modify His  : 
--===================================================================

CREATE PROCEDURE [dbo].[SP_GET_DATE_SERIAL] (
					 @I_DATESER_COLNAME VARCHAR(120),
					 @O_DATESER_CODE    VARCHAR(20) OUTPUT)
AS BEGIN 

    SET NOCOUNT ON 
    SET ANSI_WARNINGS ON

    BEGIN TRY
        BEGIN TRANSACTION        
        DECLARE @V_ERROR_SEVERITY INT,               --RAISERROR變數:ERROR_SEVERITY()
                @V_ERROR_STATE    INT,               --RAISERROR變數:ERROR_STATE()
                @V_ERROR_MESSAGE  NVARCHAR(4000),    --RAISERROR變數:ERROR_MESSAGE()
                @V_TEXT           VARCHAR(500),
                @V_SERDATE        VARCHAR(8),
                @V_DATESERNO      INT,
                @SERNO_LEN        INT,
                @V_SERDATE_TYPE   VARCHAR(1)

        SET @V_TEXT    = ''

        --========== SP START ==========

        SET @V_TEXT = '[1]找DATESERNO目前編號'        
        SELECT @V_DATESERNO = SERNO, @V_SERDATE = CONVERT(VARCHAR,SERDATE,112) FROM dbo.DATESERNO WITH(UPDLOCK) WHERE DATESER_COLNAME = @I_DATESER_COLNAME
		--SELECT @V_SERDATE_TYPE = SERDATE_TYPE FROM DATESERNO_SETS WITH(UPDLOCK) WHERE DATESER_COLNAME='EAI_WM.CTF_A_HOST_SEQ_NO'
        
        IF @V_SERDATE IS NOT NULL
        BEGIN
            IF @V_SERDATE <> CONVERT(VARCHAR,GETDATE(),112) --AND @V_SERDATE_TYPE <> 'S'
            BEGIN
                SET @V_TEXT = '[2]重新定義流水號'
                SET @V_DATESERNO = 1;
                UPDATE dbo.DATESERNO SET SERNO = @V_DATESERNO, SERDATE = GETDATE() WHERE DATESER_COLNAME = @I_DATESER_COLNAME
                SET @V_SERDATE = CONVERT(VARCHAR,GETDATE(),112)
            END
            ELSE BEGIN
                SET @V_TEXT = '[2]更新目前的流水號: '+CAST(@V_DATESERNO+1 AS VARCHAR)
                SET @V_DATESERNO = @V_DATESERNO + 1;
                UPDATE dbo.DATESERNO SET SERNO = @V_DATESERNO WHERE DATESER_COLNAME = @I_DATESER_COLNAME
            END           
        END
        ELSE BEGIN
           SET @V_TEXT = '[2]在dbo.DATESERNO找不到資料,則將序號設為NULL'
           SET @V_DATESERNO = NULL
           SET @V_SERDATE = CONVERT(VARCHAR,GETDATE(),112)
        END
        
        SET @V_TEXT = '[3]流水號長度'
        SELECT @SERNO_LEN = COALESCE(SERNO_LEN,6) FROM dbo.DATESERNO_SETS WHERE DATESER_COLNAME = @I_DATESER_COLNAME
        SET @V_DATESERNO = POWER (10,@SERNO_LEN) + @V_DATESERNO
        
--        IF @V_SERDATE_TYPE = 'S'
--	        BEGIN
--	            SET @O_DATESER_CODE = COALESCE(SUBSTRING(CONVERT(VARCHAR,@V_DATESERNO),2,LEN(@V_DATESERNO)),'')
--	        END
--        ELSE BEGIN
	        SET @V_TEXT = '[3]組日期格式' 
	        SELECT @O_DATESER_CODE = 
	            COALESCE(PREFIX_CODE,'') + 
	            CASE WHEN COALESCE(PREFIX_CODE,'') !='' THEN COALESCE(CONJ_SIGN,'') ELSE '' END + 
	            CASE WHEN SERDATE_TYPE ='A' THEN CONVERT (VARCHAR,@V_SERDATE,112) 
	            WHEN SERDATE_TYPE ='B' THEN SUBSTRING(CONVERT (VARCHAR,@V_SERDATE,112),3,8)
	            WHEN SERDATE_TYPE ='C' THEN 
	                CASE WHEN LEN(CONVERT(VARCHAR,SUBSTRING(CONVERT(VARCHAR,@V_SERDATE,112),1,4)-1911))=2 THEN '0' + CONVERT(VARCHAR,SUBSTRING(CONVERT(VARCHAR,@V_SERDATE,112),1,4)-1911) 
	                ELSE CONVERT(VARCHAR,SUBSTRING(CONVERT(VARCHAR,@V_SERDATE,112),1,4)-1911) END + SUBSTRING(CONVERT(VARCHAR,@V_SERDATE,112),5,2) + SUBSTRING(CONVERT(VARCHAR,@V_SERDATE,112),7,2)
	            WHEN SERDATE_TYPE ='D' THEN NULL
	            WHEN SERDATE_TYPE ='X' THEN ''
	            	ELSE CONVERT (VARCHAR,@V_SERDATE,112) END + COALESCE(CONJ_SIGN,'') + COALESCE(SUBSTRING(CONVERT(VARCHAR,@V_DATESERNO),2,LEN(@V_DATESERNO)),'')
	        FROM dbo.DATESERNO_SETS
	        WHERE DATESER_COLNAME = @I_DATESER_COLNAME  
--        END
        
        COMMIT TRANSACTION
        --========== SP  END  ========== 
              
    END TRY   
    BEGIN CATCH
        ROLLBACK TRANSACTION
        --產生ERROR MESSAGE:50001通知AP        
        SELECT @V_ERROR_SEVERITY = ERROR_SEVERITY(), @V_ERROR_STATE = ERROR_STATE(), @V_ERROR_MESSAGE = ERROR_MESSAGE()
        RAISERROR(50001,@V_ERROR_SEVERITY,@V_ERROR_STATE,@V_ERROR_STATE,@V_ERROR_MESSAGE)        
    END CATCH  
END

GO
EXEC sys.sp_addextendedproperty @name=N'描述', @value=N'客戶表' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CUSTOMER'
GO
EXEC sys.sp_addextendedproperty @name=N'描述', @value=N'每日生產排單' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DAILY_SCHEDULE'
GO
EXEC sys.sp_addextendedproperty @name=N'描述', @value=N'原料庫存表' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'MAT_STOCK'
GO
EXEC sys.sp_addextendedproperty @name=N'描述', @value=N'產品配方表' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRO_MATERIAL'
GO
EXEC sys.sp_addextendedproperty @name=N'描述', @value=N'產品表' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRODUCT'
GO
EXEC sys.sp_addextendedproperty @name=N'描述', @value=N'系統角色表' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ROLE'
GO
EXEC sys.sp_addextendedproperty @name=N'描述', @value=N'供應商表' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SUPPLIER'
GO
EXEC sys.sp_addextendedproperty @name=N'描述', @value=N'單位代碼表' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'UNIT'
GO
USE [master]
GO
ALTER DATABASE [MRP] SET  READ_WRITE 
GO
