USE [master]
GO
/****** Object:  Database [MRP]    Script Date: 2017/1/1 ¤U¤È 11:16:37 ******/
CREATE DATABASE [MRP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MRP', FILENAME = N'C:\db\mrp\MRP.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MRP_log', FILENAME = N'C:\db\mrp\MRP_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [MRP] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MRP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MRP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MRP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MRP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MRP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MRP] SET ARITHABORT OFF 
GO
ALTER DATABASE [MRP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MRP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MRP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MRP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MRP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MRP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MRP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MRP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MRP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MRP] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MRP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MRP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MRP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MRP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MRP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MRP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MRP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MRP] SET RECOVERY FULL 
GO
ALTER DATABASE [MRP] SET  MULTI_USER 
GO
ALTER DATABASE [MRP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MRP] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MRP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MRP] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [MRP] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'MRP', N'ON'
GO
ALTER DATABASE [MRP] SET  READ_WRITE 
GO
